= Polyglot microservices (Java, Node, .NET) + Istio on Kubernetes/OpenShift
This content is brought to you by http://developers.redhat.com - Register today!
:toc: macro
:toc-title: Table of Contents
:toclevels: 3
:icons: font
:data-uri:
:source-highlighter: highlightjs


- A HTML version of this file is published at https://redhat-scholars.github.io/istio-tutorial/

- The source code is available at https://github.com/redhat-scholars/istio-tutorial

- Download the ebook "Introducing Istio Service Mesh for Microservices" for FREE at https://developers.redhat.com/books/introducing-istio-service-mesh-microservices/.

- If you are in a hurry and want to get hands-on with Istio insanely fast, just go to http://learn.openshift.com/servicemesh[http://learn.openshift.com/servicemesh] and start instantly.



There are three different and super simple microservices in this system and they are chained together in the following sequence:

```
customer → preference → recommendation
```

= Extended demo application with Kafka integration

If you want to install the extended demo application with the Kafka integration the how-to documentation is link:README.md[here]. I created a branch for each version of the recommendation. To build the demo application run the command `make all`. In order to build each version of the recommendation, you need to check out each of the `olaf-meyer-kafka-recommendation-v*` branches and run `make recommendation`.