apiVersion: v1
kind: Template
metadata:
  name: setup_istio
parameters:
objects:
- apiVersion: maistra.io/v2
  kind: ServiceMeshControlPlane
  metadata:
    namespace: istio-system
    name: basic
  spec:
    security:
      dataPlane:
        automtls: false
    tracing:
      sampling: 10000
      type: Jaeger
    policy:
      type: Istiod
    addons:
      grafana:
        enabled: true
      jaeger:
        install:
          storage:
            type: Memory
      kiali:
        enabled: true
      prometheus:
        enabled: true
    version: v2.0
    telemetry:
      type: Istiod
- apiVersion: maistra.io/v1
  kind: ServiceMeshMemberRoll
  metadata:
    name: default
    namespace: istio-system
  spec:
    members:
      - kafka
      - demo-app

